# Generated by Django 4.2.4 on 2023-09-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
    ]
