# Generated by Django 4.2.4 on 2023-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dsdsda', upload_to='gallary'),
            preserve_default=False,
        ),
    ]
